export const exchanges = [
  {
    name: "Kraken",
    url: "https://www.kraken.com/learn/buy-kaspa-kas",
    logo: "/exchanges/kraken.svg",
    logoWidth: 286,
    logoHeight: 46,
    bg: "#7132F5",
  },
  {
    name: "KuCoin",
    url: "https://www.kucoin.com/how-to-buy/kaspa",
    logo: "/exchanges/kucoin.svg",
    logoWidth: 271,
    logoHeight: 64,
    bg: "#00B47D",
  },
  {
    name: "MEXC",
    url: "https://www.mexc.com/how-to-buy/KAS",
    logo: "/exchanges/mexc.svg",
    logoWidth: 271,
    logoHeight: 39,
    bg: "#0043FF",
  },
  {
    name: "CoinEx",
    url: "https://www.coinex.com/s/buy-kaspa",
    logo: "/exchanges/coinex.svg",
    logoWidth: 287,
    logoHeight: 72,
    bg: "linear-gradient(to right, #22E6B8, #11D4C3, #00C1CE)",
  },
  {
    name: "Bybit",
    url: "https://www.bybit.com/en/how-to-buy/kaspa/",
    logo: "/exchanges/bybit.svg",
    logoWidth: 176,
    logoHeight: 59,
    bg: "#000",
  },
  {
    name: "Gate",
    url: "https://www.gate.io/how-to-buy/kaspa",
    logo: "/exchanges/gate.svg",
    logoWidth: 237,
    logoHeight: 54,
    bg: "#fff",
  },
  {
    name: "BingX",
    url: "https://bingx.com/en-us/how-to-buy/kaspa/",
    logo: "/exchanges/bingx.svg",
    logoWidth: 92,
    logoHeight: 29,
    bg: "#000",
  },
  {
    name: "Bitget",
    url: "https://www.bitget.com/how-to-buy/kaspa",
    logo: "/exchanges/bitget.svg",
    logoWidth: 90,
    logoHeight: 27,
    bg: "#00F0FF",
  },
  {
    name: "WEEX",
    url: "https://www.weex.com/pl/futures/KAS-USDT",
    logo: "/exchanges/weex.svg",
    logoWidth: 119,
    logoHeight: 25,
    bg: "#D8AE15",
  },
  {
    name: "BitMart",
    url: "https://www.bitmart.com/trade/KAS_USDT",
    logo: "/exchanges/bitmart.svg",
    logoWidth: 100,
    logoHeight: 25,
    bg: "#000",
  },
  {
    name: "OurBit",
    url: "https://www.ourbit.com/exchange/KAS_USDT?_from=market",
    logo: "/exchanges/ourbit.svg",
    logoWidth: 99,
    logoHeight: 25,
    bg: "#fff",
  },
  {
    name: "BYDFi",
    url: "https://www.bydfi.com/en/spot/kas_usdt",
    logo: "/exchanges/bydfi.svg",
    logoWidth: 241,
    logoHeight: 59,
    bg: "#000",
  },
  {
    name: "LBank",
    url: "https://www.lbank.info/trade/kas_usdt",
    logo: "/exchanges/lbank.svg",
    logoWidth: 204,
    logoHeight: 41,
    bg: "#000",
  },
  {
    name: "CoinW",
    url: "https://www.coinw.com/spot/kasusdt",
    logo: "/exchanges/coinw.svg",
    logoWidth: 254,
    logoHeight: 63,
    bg: "#5227FF",
  },
] as const;
